@startuml

!startsub public_declaration
!ifndef COL_IMPL_PUBLIC
!define COL_IMPL_PUBLIC

!includesub ArrayBase.puml!public_declaration
!includesub DoubleLinkedList.puml!public_declaration

!endif
!endsub

@enduml