@startuml

!includesub ../channel/Channel.puml!public_declaration

!startsub public_declaration
!ifndef MAP_SERVER_PUBLIC
!define MAP_SERVER_PUBLIC

namespace cds {
    namespace __hidden {
        namespace __impl {

            abstract class __CollectionInternalCommunicationChannel

            note "To be implemented by classes derived from CDS/Map\nand, ideally, alongside __MapServerDispatcher" as MSUsage

            interface __MapServer <R, E> {
                - {field} {static} __routingTable : __GenericHandler const []
                - {field} {static} __constRoutingTable : __GenericConstHandler const []
                # {method} __ms_handlers () const noexcept -> __GenericHandler const *
                # {method} __ms_constHandlers () const noexcept -> __GenericConstHandler const *
            }

            __MapServer "provides generic handler list" .. cds.__hidden.__impl.__CollectionInternalCommunicationChannel

            MSUsage . __MapServer

        }
    }
}

!endif
!endsub

@enduml