@startuml

!includesub ../channel/Channel.puml!public_declaration

!startsub public_declaration
!ifndef MUTABLE_COLLECTION_SERVER_PUBLIC
!define MUTABLE_COLLECTION_SERVER_PUBLIC

namespace cds {
    namespace __hidden {
        namespace __impl {

            abstract class __CollectionInternalCommunicationChannel

            note "To be implemented by classes derived from CDS/MutableCollection\nand, ideally, alongside __MutableCollectionServerDispatcher" as MCSUsage

            interface __MutableCollectionServer <R, E> {
                - {field} {static} __routingTable : __GenericHandler const []
                - {field} {static} __constRoutingTable : __GenericConstHandler const []
                # {method} __mcs_handlers () const noexcept -> __GenericHandler const *
                # {method} __mcs_constHandlers () const noexcept -> __GenericConstHandler const *
            }

            __MutableCollectionServer "provides generic handler list" .. cds.__hidden.__impl.__CollectionInternalCommunicationChannel

            MCSUsage . __MutableCollectionServer

        }
    }
}

!endif
!endsub

@enduml