@startuml

!includesub ../primitive/DelegateForwardConstIterablePrimitiveClient.puml!public_declaration

!startsub public_declaration
!ifndef CONTAINS_COMPOSITE_PUBLIC
!define CONTAINS_COMPOSITE_PUBLIC

namespace cds {

    namespace __hidden {
        namespace __impl {

            interface __DelegateForwardConstIterablePrimitiveClient
            interface __LocalDelegateForwardConstIterablePrimitiveClient

            interface __ContainsOfCompositeClient <R, E, I, BiPredicate <I, E>> {
                + {method} containsAnyOf (I const &) const noexcept -> bool
                + {method} containsAnyNotOf (I const &) const noexcept -> bool
                + {method} containsAll (I const &) const noexcept -> bool
                + {method} containsNoneOf (I const &) const noexcept -> bool
            }

            class __LocalContainsOfCompositeClient <R, E, I, BIPredicate <I, E>> << (T, #aa9999) >>
            __ContainsOfCompositeClient .. "is " __LocalContainsOfCompositeClient
            __DelegateForwardConstIterablePrimitiveClient .. "uses" __ContainsOfCompositeClient
            __LocalDelegateForwardConstIterablePrimitiveClient ... "uses" __LocalContainsOfCompositeClient

        }
    }
}

!endif
!endsub

@enduml