@startuml

!includesub String.puml!public_declaration

!startsub public_declaration

namespace cds {

    abstract class Object {
        ..default methods..
        # {method} Object () noexcept
        # {method} Object (Object const &) noexcept
        # {method} Object (Object &&) noexcept
        ..default overloaded operators..
        # {method} operator = (Object const &) noexcept -> Object &
        # {method} operator = (Object &&) noexcept -> Object &
        ..methods with default implementation..
        + {method} {abstract} toString () const noexcept -> String
        + {method} {abstract} equals (Object const &) const noexcept -> bool
        + {method} {abstract} hash () const noexcept -> Size
        + {method} {abstract} ~Object () noexcept
        ..overloaded operators..
        + {method} {static} operator << (std::ostream &, Object const &) noexcept -> std::ostream &
        + {method} operator String () const noexcept
    }

    Object "toString(), cast -> yields" -- String

}

!endsub

@enduml