@startuml

!startsub public_declaration
!ifndef ALL_ITERATOR_PUBLIC
!define ALL_ITERATOR_PUBLIC

!includesub IteratorModel.puml!public_declaration
!includesub NodeModel.puml!public_declaration
!includesub HashTableIterator.puml!public_declaration
!includesub AddressIterator.puml!public_declaration
!includesub NodeIterator.puml!public_declaration

!endif
!endsub

@enduml