@startuml

!startsub public_declaration
!ifndef NODE_MODEL_PUBLIC
!define NODE_MODEL_PUBLIC

namespace cds {
    namespace __hidden {
        namespace __impl {

            class __UnidirectionalNode <E> {
                + {field} _data : E
                + {field} _pNext : __UnidirectionalNode <E> *
            }

            __UnidirectionalNode "1" o-- "1" __UnidirectionalNode

            class __BidirectionalNode <E> {
                + {field} _data : E
                + {field} _pNext : __BidirectionalNode <E> *
                + {field} _pPrevious : __BidirectionalNode <E> *
            }

            __BidirectionalNode "1" o-- "2" __BidirectionalNode

            enum __RedBlackTreeNodeColour {
                + {field} {static} __rbtnc_Black
                + {field} {static} __rbtnc_Red
            }

            class __RedBlackTreeNode <E> {
                + {field} _data : E
                + {field} __RedBlackTreeNodeColour _colour
                + {field} _pLeft : __RedBlackTreeNode <E> *
                + {field} _pRight : __RedBlackTreeNode <E> *
                + {field} _pParent : __RedBlackTreeNode <E> *
            }

            __RedBlackTreeNode::_colour "1" *-- "1" __RedBlackTreeNodeColour
            __RedBlackTreeNode "1" o- "3" __RedBlackTreeNode

        }
    }
}

!endif
!endsub

@enduml