@startuml

!includesub ../../../primitives/baseTypes/Object.puml!public_declaration

!startsub public_declaration
!ifndef COLLECTION_COMMUNICATION_CHANNEL_PUBLIC
!define COLLECTION_COMMUNICATION_CHANNEL_PUBLIC

namespace cds {

    abstract class Object

    namespace __hidden {
        namespace __impl {

            note "Every Abstract-to-Derived Object Model\nimplementing Client-to-Server methods\nwill extend the base class from this" as CICCHAbsDerivNote
            note "Derived objects are required to derive these methods and provide\nappropriate receiver handlers. Ideally, a Server is used to provide\nthe handlers, and a Dispatcher to provide the standard functions\nto the server" as CICCHDerivHint

            abstract class __CollectionInternalCommunicationChannel <R, E> {
                # {method} __CollectionInternalCommunicationChannel () noexcept
                # {method} __CollectionInternalCommunicationChannel (__CollectionInternalCommunicationChannel const &) noexcept
                # {method} __CollectionInternalCommunicationChannel (__CollectionInternalCommunicationChannel &) noexcept
                # {method} operator = (__CollectionInternalCommunicationChannel const &) noexcept -> __CollectionInternalCommunicationChannel &
                # {method} operator = (__CollectionInternalCommunicationChannel &&) noexcept -> __CollectionInternalCommunicationChannel &
                + {method} ~__CollectionInternalCommunicationChannel () noexcept

                # {method} {abstract} __cicch_obtainGenericHandler (__CollectionInternalRequestType) noexcept -> __GenericHandler
                # {method} {abstract} __cicch_obtainGenericConstHandler (__CollectionInternalRequestType) const noexcept -> __GenericConstHandler
            }

            cds.Object <|-- __CollectionInternalCommunicationChannel

            interface __DelegateForwardIterablePrimitiveClient <R, E, bidirectional>
            interface __DelegateBackwardIterablePrimitiveClient <R, E, bidirectional>
            interface __DelegateForwardConstIterablePrimitiveClient <R, E, bidirectional>
            interface __DelegateBackwardConstIterablePrimitiveClient <R, E, bidirectional>
            interface __AbstractIteratorRemovePrimitiveClient <R, E>
            interface __AbstractConstIteratorRemovePrimitiveClient <R, E>
            interface __RandomInsertionPrimitiveClient <R, E, RV>
            interface __BoundaryInsertionPrimitiveClient <R, E, RV>
            interface __AbstractIteratorRelativeInsertionPrimitiveClient <R, E>
            interface __AbstractConstIteratorRelativeInsertionPrimitiveClient <R, E>
            interface __FindUniqueImmutablePrimitiveClient <R, E, K, bidirectional>
            interface __FindUniqueMutablePrimitiveClient <R, E, K, bidirectional>

            <> PrivateAccessRef

            CICCHAbsDerivNote -- __CollectionInternalCommunicationChannel
            CICCHDerivHint - "__CollectionInternalCommunicationChannel::__cicch_obtainGenericHandler"
            CICCHDerivHint - "__CollectionInternalCommunicationChannel::__cicch_obtainGenericConstHandler"

        }
    }
}

cds.__hidden.__impl.__CollectionInternalCommunicationChannel "allows private access to" - PrivateAccessRef
PrivateAccessRef .. cds.__hidden.__impl.__DelegateForwardIterablePrimitiveClient
PrivateAccessRef .. cds.__hidden.__impl.__DelegateBackwardIterablePrimitiveClient
PrivateAccessRef .. cds.__hidden.__impl.__DelegateForwardConstIterablePrimitiveClient
PrivateAccessRef ... cds.__hidden.__impl.__DelegateBackwardConstIterablePrimitiveClient
PrivateAccessRef ... cds.__hidden.__impl.__AbstractIteratorRemovePrimitiveClient
PrivateAccessRef ... cds.__hidden.__impl.__AbstractConstIteratorRemovePrimitiveClient
PrivateAccessRef .... cds.__hidden.__impl.__RandomInsertionPrimitiveClient
PrivateAccessRef .... cds.__hidden.__impl.__BoundaryInsertionPrimitiveClient
PrivateAccessRef .... cds.__hidden.__impl.__AbstractIteratorRelativeInsertionPrimitiveClient
PrivateAccessRef ..... cds.__hidden.__impl.__AbstractConstIteratorRelativeInsertionPrimitiveClient
PrivateAccessRef ..... cds.__hidden.__impl.__FindUniqueImmutablePrimitiveClient
PrivateAccessRef ..... cds.__hidden.__impl.__FindUniqueMutablePrimitiveClient

!endif
!endsub

@enduml