@startuml


!includesub ../../primitives/baseTypes/Object.puml!public_declaration
!includesub AbstractDelegateIterator.puml!public_declaration
!includesub IteratorAdvanceDirection.puml!public_declaration
!includesub ../collectionCommunication/client/primitive/IteratorRelativeInsertionPrimitiveClient.puml!public_declaration
!includesub ../collectionCommunication/client/primitive/ConstIteratorRelativeInsertionPrimitiveClient.puml!public_declaration
!includesub ../collectionCommunication/client/primitive/IteratorRemovePrimitiveClient.puml!public_declaration
!includesub ../collectionCommunication/client/primitive/ConstIteratorRemovePrimitiveClient.puml!public_declaration

!startsub public_declaration
!ifndef ABS_DEL_WR_IT_PUBLIC
!define ABS_DEL_WR_IT_PUBLIC

namespace cds {

    abstract class Object

    namespace __hidden {
        namespace __impl {

            abstract class __AbstractDelegateIterator
            interface __AbstractIteratorRelativeInsertionPrimitiveClient
            interface __AbstractIteratorRemovePrimitiveClient
            interface __AbstractConstIteratorRelativeInsertionPrimitiveClient
            interface __AbstractConstIteratorRemovePrimitiveClient

            abstract class __AbstractDelegateWrapperIterator <E> {
                - {field} _pOwner : cds::Object const *
                - {field} _pDelegate : __AbstractDelegateIterator <E> *
                ..base methods..
                # {method} __AbstractDelegateWrapperIterator () noexcept
                # {method} __AbstractDelegateWrapperIterator (cds::Object const &, __AbstractDelegateIterator <E> *) noexcept
                # {method} __AbstractDelegateWrapperIterator (__AbstractDelegateWrapperIterator const &) noexcept
                # {method} __AbstractDelegateWrapperIterator (__AbstractDelegateWrapperIterator &&) noexcept
                + {method} {abstract} ~__AbstractDelegateWrapperIterator () noexcept
                ..protected methods..
                # {method} advance (__IteratorAdvanceDirection) noexcept -> __AbstractDelegateWrapperIterator &
                # {method} equals (__AbstractDelegateWrapperIterator const &) const noexcept -> bool
                # {method} value (__AbstractDelegateWrapperIterator const &) const noexcept -> bool
                # {method} of (cds::Object const *) const noexcept -> bool
                # {method} copy (__AbstractDelegateWrapperIterator const &) noexcept -> __AbstractDelegateWrapperIterator &
                # {method} move (__AbstractDelegateWrapperIterator &&) noexcept -> __AbstractDelegateWrapperIterator &
                ..public methods..
                + {method} operator bool () const noexcept
                + {method} operator * () const noexcept -> E &
                + {method} operator -> () const noexcept -> E *
            }

            cds.Object "1" --o "1" __AbstractDelegateWrapperIterator
            __AbstractDelegateWrapperIterator "1" *--- "1" __AbstractDelegateIterator

            note "Grants Private Access to users through" as ADWIHin
            ADWIHin . __AbstractDelegateWrapperIterator

            class __AbstractIteratorRelativeInsertionPrimitiveClient::AbstractIterator << (T, #aa9999) >>
            class __AbstractIteratorRemovePrimitiveClient::AbstractIterator << (T, #aa9999) >>
            class __AbstractConstIteratorRelativeInsertionPrimitiveClient::AbstractConstIterator << (T, #aa9999) >>
            class __AbstractConstIteratorRemovePrimitiveClient::AbstractConstIterator << (T, #aa9999) >>

            __AbstractIteratorRelativeInsertionPrimitiveClient::AbstractIterator "nested in" .. __AbstractIteratorRelativeInsertionPrimitiveClient
            __AbstractIteratorRemovePrimitiveClient::AbstractIterator "nested in" .. __AbstractIteratorRemovePrimitiveClient
            __AbstractConstIteratorRelativeInsertionPrimitiveClient::AbstractConstIterator "nested in" .. __AbstractConstIteratorRelativeInsertionPrimitiveClient
            __AbstractConstIteratorRemovePrimitiveClient::AbstractConstIterator "nested in" .. __AbstractConstIteratorRemovePrimitiveClient

            __AbstractDelegateWrapperIterator ..... "is" __AbstractIteratorRelativeInsertionPrimitiveClient::AbstractIterator
            __AbstractDelegateWrapperIterator .... "is" __AbstractIteratorRemovePrimitiveClient::AbstractIterator
            __AbstractDelegateWrapperIterator ..... "is" __AbstractConstIteratorRelativeInsertionPrimitiveClient::AbstractConstIterator
            __AbstractDelegateWrapperIterator .... "is" __AbstractConstIteratorRemovePrimitiveClient::AbstractConstIterator

        }
    }
}

!endif
!endsub

remove cds.__hidden.__impl.__Local*
remove cds.__hidden.__impl.*Hint

@enduml