@startuml

!includesub AbstractDelegateWrapperIterator.puml!public_declaration
!includesub ../iterator/IteratorModel.puml!public_declaration

!startsub public_declaration
!ifndef BI_DEL_WR_IT_PUBLIC
!define BI_DEL_WR_IT_PUBLIC

namespace cds {

    namespace __hidden {
        namespace __impl {

            class __BidirectionalDelegateWrapperIterator <E> extends __AbstractDelegateWrapperIterator implements cds.meta.BidirectionalIterator {
                + {method} __BidirectionalDelegateWrapperIterator () noexcept
                + {method} __BidirectionalDelegateWrapperIterator (cds::Object const &, __AbstractDelegateIterator <E> *) noexcept
                + {method} __BidirectionalDelegateWrapperIterator (__BidirectionalDelegateWrapperIterator const &) noexcept
                + {method} __BidirectionalDelegateWrapperIterator (__BidirectionalDelegateWrapperIterator &&) noexcept
                + {method} ~__ForwardDelegateWrapperIterator () noexcept
                + {method} operator = (__BidirectionalDelegateWrapperIterator const &) noexcept -> __BidirectionalDelegateWrapperIterator &
                + {method} operator = (__BidirectionalDelegateWrapperIterator &&) noexcept -> __BidirectionalDelegateWrapperIterator &

                + {method} operator == (__BidirectionalDelegateWrapperIterator const &) const noexcept -> bool
                + {method} operator != (__BidirectionalDelegateWrapperIterator const &) const noexcept -> bool
                + {method} operator ++ () noexcept -> __BidirectionalDelegateWrapperIterator &
                + {method} operator -- () noexcept -> __BidirectionalDelegateWrapperIterator &
            }

        }
    }
}

!endif
!endsub

@enduml