@startuml

!includesub ../../channel/Channel.puml!public_declaration

!startsub public_declaration
!ifndef BACK_PUBLIC
!define BACK_PUBLIC

namespace cds {
    namespace __hidden {
        namespace __impl {

            interface __DelegateBackwardIterablePrimitiveClient <R, E, bidirectional> {
                + {method} rbegin () noexcept -> ReverseIterator
                + {method} rend () noexcept -> ReverseIterator
            }

            interface __LocalDelegateBackwardIterablePrimitiveClient <R, I> {
                + {method} rbegin () noexcept -> I
                + {method} rend () noexcept -> I
            }

            note "Requests direct dispatcher-standard calls" as DBIPCLocalHint
            note "Requests handlers to call through Channel" as DBIPCHint
            DBIPCLocalHint - __LocalDelegateBackwardIterablePrimitiveClient
            DBIPCHint - __DelegateBackwardIterablePrimitiveClient

        }
    }
}

!endif
!endsub

@enduml