@startuml

!includesub ../../channel/Channel.puml!public_declaration

!startsub public_declaration
!ifndef BACK_CONST_PUBLIC
!define BACK_CONST_PUBLIC

namespace cds {
    namespace __hidden {
        namespace __impl {

            interface __DelegateBackwardConstIterablePrimitiveClient <R, E, bidirectional> {
                + {method} rbegin () const noexcept -> ConstReverseIterator
                + {method} rend () const noexcept -> ConstReverseIterator
                + {method} crbegin () const noexcept -> ConstReverseIterator
                + {method} crend () const noexcept -> ConstReverseIterator
            }

            interface __LocalDelegateBackwardConstIterablePrimitiveClient <R, CRIT> {
                + {method} rbegin () const noexcept -> CRIT
                + {method} rend () const noexcept -> CRIT
                + {method} crbegin () const noexcept -> CRIT
                + {method} crend () const noexcept -> CRIT
            }

            note "Requests direct dispatcher-standard calls" as DBCIPCLocalHint
            note "Requests handlers to call through Channel" as DBCIPCHint
            DBCIPCLocalHint - __LocalDelegateBackwardConstIterablePrimitiveClient
            DBCIPCHint - __DelegateBackwardConstIterablePrimitiveClient

        }
    }
}

!endif
!endsub

@enduml