@startuml

!includesub ../../channel/Channel.puml!public_declaration

!startsub public_declaration
!ifndef FORW_PUBLIC
!define FORW_PUBLIC

namespace cds {
    namespace __hidden {
        namespace __impl {

            interface __DelegateForwardIterablePrimitiveClient <R, E, bidirectional> {
                + {method} begin () noexcept -> Iterator
                + {method} end () noexcept -> Iterator
            }

            interface __LocalDelegateForwardIterablePrimitiveClient <R, IT> {
                + {method} begin () noexcept -> IT
                + {method} end () noexcept -> IT
            }

            note "Requests direct dispatcher-standard calls" as DFIPCLocalHint
            note "Requests handlers to call through Channel" as DFIPCHint
            DFIPCLocalHint - __LocalDelegateForwardIterablePrimitiveClient
            DFIPCHint - __DelegateForwardIterablePrimitiveClient

        }
    }
}

!endif
!endsub

@enduml