@startuml

!includesub ../../channel/Channel.puml!public_declaration

!startsub public_declaration
!ifndef FIND_PUBLIC
!define FIND_PUBLIC

namespace cds {
    namespace __hidden {
        namespace __impl {

            interface __FindUniqueMutablePrimitiveClient <R, E, K, bidirectional> {
                + {method} find (K const &) noexcept -> Iterator
            }

            interface __LocalFindUniqueMutablePrimitiveClient <R, K, I, bidirectional> {
                + {method} find (K const &) noexcept -> I
            }

            note "Requests direct dispatcher-standard calls" as FUMPCLocalHint
            note "Requests handlers to call through Channel" as FUMPCHint
            FUMPCLocalHint - __LocalFindUniqueMutablePrimitiveClient
            FUMPCHint - __FindUniqueMutablePrimitiveClient

        }
    }
}

!endif
!endsub

@enduml