@startuml

!includesub ../../channel/Channel.puml!public_declaration

!startsub public_declaration
!ifndef REMOVE_PUBLIC
!define REMOVE_PUBLIC

namespace cds {
    namespace __hidden {
        namespace __impl {

            interface __AbstractIteratorRemovePrimitiveClient <R, E> {
                + {method} remove (AbstractIterator const &) noexcept -> bool
                - {method} removeAll (AbstractIterator const *, Size) noexcept -> Size
            }

            interface __LocalIteratorRemovePrimitiveClient <R, E, I> {
                + {method} remove (I const &) noexcept -> bool
                - {method} removeAll (I const *, Size) noexcept -> Size
            }

            note "Requests direct dispatcher-standard calls" as LIRPCLocalHint
            note "Requests handlers to call through Channel" as AIRPCHint
            LIRPCLocalHint - __LocalIteratorRemovePrimitiveClient
            AIRPCHint - __AbstractIteratorRemovePrimitiveClient

        }
    }
}

!endif
!endsub

@enduml