@startuml

!include Collection.puml

!startsub public_declaration
!ifndef COLLECTION_ALL_PUBLIC
!define COLLECTION_ALL_PUBLIC

!includesub Collection.puml!public_declaration
!includesub MutableCollection.puml!public_declaration
!includesub Set.puml!public_declaration
!includesub Map.puml!public_declaration
!includesub List.puml!public_declaration
!includesub Array.puml!public_declaration

!endif
!endsub

!startsub private
remove cds.__hidden.__impl.__*Local*
remove *LocalHint*
!endsub

@enduml