@startuml

!includesub MutableCollection.puml!public_declaration

!includesub ../shared/collectionCommunication/client/primitive/DelegateForwardIterablePrimitiveClient.puml!public_declaration
!includesub ../shared/collectionCommunication/client/primitive/DelegateForwardConstIterablePrimitiveClient.puml!public_declaration
!includesub ../shared/collectionCommunication/client/primitive/DelegateBackwardIterablePrimitiveClient.puml!public_declaration
!includesub ../shared/collectionCommunication/client/primitive/DelegateBackwardConstIterablePrimitiveClient.puml!public_declaration
!includesub ../shared/collectionCommunication/client/primitive/IteratorRemovePrimitiveClient.puml!public_declaration
!includesub ../shared/collectionCommunication/client/primitive/ConstIteratorRemovePrimitiveClient.puml!public_declaration
!includesub ../shared/collectionCommunication/client/primitive/IteratorRelativeInsertionPrimitiveClient.puml!public_declaration
!includesub ../shared/collectionCommunication/client/primitive/ConstIteratorRelativeInsertionPrimitiveClient.puml!public_declaration
!includesub ../shared/collectionCommunication/client/primitive/BoundaryInsertionPrimitiveClient.puml!public_declaration
!includesub ../shared/collectionCommunication/client/primitive/IndexedOperationsPrimitiveClient.puml!public_declaration

!includesub ../shared/collectionCommunication/client/composite/ReplaceCompositeClient.puml!public_declaration
!includesub ../shared/collectionCommunication/client/composite/ReplaceOfCompositeClient.puml!public_declaration
!includesub ../shared/collectionCommunication/client/composite/ReplaceByCompositeClient.puml!public_declaration
!includesub ../shared/collectionCommunication/client/composite/IndicesCompositeClient.puml!public_declaration
!includesub ../shared/collectionCommunication/client/composite/IndicesOfCompositeClient.puml!public_declaration
!includesub ../shared/collectionCommunication/client/composite/IndicesByCompositeClient.puml!public_declaration

!startsub public_declaration
!ifndef LIST_PUBLIC
!define LIST_PUBLIC

namespace cds {

    namespace __hidden {
        namespace __impl {

            interface __DelegateForwardIterablePrimitiveClient
            interface __DelegateForwardConstIterablePrimitiveClient
            interface __DelegateBackwardIterablePrimitiveClient
            interface __DelegateBackwardConstIterablePrimitiveClient
            interface __BoundaryInsertionPrimitiveClient
            interface __AbstractIteratorRelativeInsertionPrimitiveClient
            interface __AbstractConstIteratorRelativeInsertionPrimitiveClient
            interface __IndexedOperationsPrimitiveClient
            interface __ReplaceCompositeClient
            interface __ReplaceOfCompositeClient
            interface __ReplaceByCompositeClient
            interface __IndicesCompositeClient
            interface __IndicesOfCompositeClient
            interface __IndicesByCompositeClient

            class __ListDelegateForwardIterableClient <E> << (T, #aa9999) >>
            class __ListDelegateForwardConstIterableClient <E> << (T, #aa9999) >>
            class __ListDelegateBackwardIterableClient <E> << (T, #aa9999) >>
            class __ListDelegateBackwardConstIterableClient <E> << (T, #aa9999) >>
            class __ListBoundaryInsertionClient <E> << (T, #aa9999) >>
            class __ListIteratorRelativeInsertionClient <E> << (T, #aa9999) >>
            class __ListConstIteratorRelativeInsertionClient <E> << (T, #aa9999) >>
            class __ListIndexedOperationsClient <E> << (T, #aa9999) >>
            class __ListReplaceClient <E> << (T, #aa9999) >>
            class __ListReplaceOfCollectionClient <E> << (T, #aa9999) >>
            class __ListReplaceOfInitializerListClient <E> << (T, #aa9999) >>
            class __ListReplaceByClient <E> << (T, #aa9999) >>
            class __ListIndicesClient <E> << (T, #aa9999) >>
            class __ListIndicesOfCollectionClient <E> << (T, #aa9999) >>
            class __ListIndicesOfInitializerListClient <E> << (T, #aa9999) >>
            class __ListIndicesByClient <E> << (T, #aa9999) >>

            __DelegateForwardIterablePrimitiveClient .......... "is" __ListDelegateForwardIterableClient
            __DelegateForwardConstIterablePrimitiveClient .......... "is" __ListDelegateForwardConstIterableClient
            __DelegateBackwardIterablePrimitiveClient .......... "is" __ListDelegateBackwardIterableClient
            __DelegateBackwardConstIterablePrimitiveClient ......... "is" __ListDelegateBackwardConstIterableClient
            __BoundaryInsertionPrimitiveClient ......... "is" __ListBoundaryInsertionClient
            __AbstractIteratorRelativeInsertionPrimitiveClient .......... "is" __ListIteratorRelativeInsertionClient
            __AbstractConstIteratorRelativeInsertionPrimitiveClient ......... "is" __ListConstIteratorRelativeInsertionClient
            __IndexedOperationsPrimitiveClient ......... "is" __ListIndexedOperationsClient
            __ReplaceCompositeClient ......... "is" __ListReplaceClient
            __ReplaceOfCompositeClient ......... "is" __ListReplaceOfCollectionClient
            __ReplaceOfCompositeClient ......... "is" __ListReplaceOfInitializerListClient
            __ReplaceByCompositeClient ......... "is" __ListReplaceByClient
            __IndicesCompositeClient ......... "is" __ListIndicesClient
            __IndicesOfCompositeClient ......... "is" __ListIndicesOfCollectionClient
            __IndicesOfCompositeClient ......... "is" __ListIndicesOfInitializerListClient
            __IndicesByCompositeClient ......... "is" __ListIndicesByClient

        }
    }

    abstract class MutableCollection <E>
    abstract class List <E> extends MutableCollection implements cds.__hidden.__impl.__ListDelegateForwardIterableClient, cds.__hidden.__impl.__ListDelegateForwardConstIterableClient, cds.__hidden.__impl.__ListDelegateBackwardIterableClient, cds.__hidden.__impl.__ListDelegateBackwardConstIterableClient, cds.__hidden.__impl.__ListBoundaryInsertionClient, cds.__hidden.__impl.__ListIteratorRelativeInsertionClient, cds.__hidden.__impl.__ListConstIteratorRelativeInsertionClient, cds.__hidden.__impl.__ListIndexedOperationsClient, cds.__hidden.__impl.__ListReplaceClient, cds.__hidden.__impl.__ListReplaceOfCollectionClient, cds.__hidden.__impl.__ListReplaceOfInitializerListClient, cds.__hidden.__impl.__ListReplaceByClient, cds.__hidden.__impl.__ListIndicesClient, cds.__hidden.__impl.__ListIndicesOfCollectionClient, cds.__hidden.__impl.__ListIndicesOfInitializerListClient, cds.__hidden.__impl.__ListIndicesByClient {
        ..base methods..
        # {method} List () noexcept
        # {method} List (List const &) noexcept
        # {method} List (List &&) noexcept
        # {method} {abstract} ~List () noexcept
        ..public methods..
        + {method} toString () const noexcept -> String
        + {method} {abstract} popFront () noexcept -> void
        + {method} {abstract} popBack () noexcept -> void
        + {method} {abstract} front () throws OutOfBoundsException -> E &
        + {method} {abstract} front () const throws OutOfBoundsException -> E const &
        + {method} {abstract} back () throws OutOfBoundsException -> E &
        + {method} {abstract} back () const throws OutOfBoundsException -> E const &
        + {method} {abstract} get (Index) throws OutOfBoundsException -> E &
        + {method} {abstract} get (Index) const throws OutOfBoundsException -> E const &
        + {method} {abstract} sort (BiPredicate <E, E> const &) const throws OutOfBoundsException -> E const &
        + {method} {abstract} removeAt (Index) noexcept -> bool
        # {method} {abstract} circularAdjustedIndex (Index) const noexcept -> Index
    }

}

!endif
!endsub

!startsub private
remove cds.__hidden.__impl.__*Local*
remove *LocalHint*
!endsub

@enduml