@startuml

!includesub Collection.puml!public_declaration

!includesub ../shared/collectionCommunication/client/primitive/FindUniqueImmutablePrimitiveClient.puml!public_declaration

!startsub public_declaration
!ifndef SET_PUBLIC
!define SET_PUBLIC

namespace cds {

    namespace __hidden {
        namespace __impl {

            interface __FindUniqueImmutablePrimitiveClient

            class __SetFindUniqueClient <E> << (T, #aa9999) >>

            __FindUniqueImmutablePrimitiveClient ......... "is" __SetFindUniqueClient

        }
    }

    abstract class Collection <E>
    abstract class Set <E> extends Collection implements cds.__hidden.__impl.__SetFindUniqueClient {
        ..base methods..
        # {method} Set () noexcept
        # {method} Set (Set const &) noexcept
        # {method} Set (Set &&) noexcept
        + {method} {abstract} ~Set () noexcept
        ..public methods..
        + {method} toString () const noexcept -> String
        + {method} {abstract} remove (E const &) noexcept -> bool
    }

}

!endif
!endsub

!startsub private
remove cds.__hidden.__impl.__*Local*
remove *LocalHint*
!endsub

@enduml