//
// Created by loghin on 6/26/22.
//

#ifndef __CDS_SHARED_ITERABLE_TAKE_BY_PREDICATE_IMPL_HPP__
#define __CDS_SHARED_ITERABLE_TAKE_BY_PREDICATE_IMPL_HPP__

#endif // __CDS_SHARED_ITERABLE_TAKE_BY_PREDICATE_IMPL_HPP__
