@startuml

!include ../subsets/primitives/baseTypes/Object.puml
!include ../subsets/primitives/baseTypes/String.puml

!include ../subsets/shared/iterator/IteratorModel.puml
!include ../subsets/shared/iterator/AddressIterator.puml

!include ../subsets/shared/collectionCommunication/RequestType.puml
!include ../subsets/shared/collectionCommunication/channel/Channel.puml
!include ../subsets/shared/collectionCommunication/server/CollectionServerDispatcher.puml
!include ../subsets/shared/collectionCommunication/server/ListServer.puml
!include ../subsets/shared/collectionCommunication/server/ListServerDispatcher.puml
!include ../subsets/shared/collectionCommunication/server/MapServer.puml
!include ../subsets/shared/collectionCommunication/server/MapServerDispatcher.puml
!include ../subsets/shared/collectionCommunication/server/MutableCollectionServer.puml
!include ../subsets/shared/collectionCommunication/server/MutableCollectionServerDispatcher.puml
!include ../subsets/shared/collectionCommunication/server/SetServer.puml
!include ../subsets/shared/collectionCommunication/server/SetServerDispatcher.puml

@enduml