@startuml

!include ../subsets/primitives/baseTypes/Object.puml
!include ../subsets/primitives/baseTypes/String.puml

!include ../subsets/shared/iterator/IteratorModel.puml
!include ../subsets/shared/iterator/AddressIterator.puml

!include ../subsets/shared/collectionCommunication/RequestType.puml

!include ../subsets/shared/collectionCommunication/channel/Channel.puml

!include ../subsets/shared/collectionCommunication/server/CollectionServerDispatcher.puml
!include ../subsets/shared/collectionCommunication/server/ListServer.puml
!include ../subsets/shared/collectionCommunication/server/ListServerDispatcher.puml
!include ../subsets/shared/collectionCommunication/server/MapServer.puml
!include ../subsets/shared/collectionCommunication/server/MapServerDispatcher.puml
!include ../subsets/shared/collectionCommunication/server/MutableCollectionServer.puml
!include ../subsets/shared/collectionCommunication/server/MutableCollectionServerDispatcher.puml
!include ../subsets/shared/collectionCommunication/server/SetServer.puml
!include ../subsets/shared/collectionCommunication/server/SetServerDispatcher.puml

!include ../subsets/shared/collectionCommunication/client/primitive/BoundaryInsertionPrimitiveClient.puml
!include ../subsets/shared/collectionCommunication/client/primitive/ConstIteratorRelativeInsertionPrimitiveClient.puml
!include ../subsets/shared/collectionCommunication/client/primitive/ConstIteratorRemovePrimitiveClient.puml
!include ../subsets/shared/collectionCommunication/client/primitive/DelegateBackwardConstIterablePrimitiveClient.puml
!include ../subsets/shared/collectionCommunication/client/primitive/DelegateBackwardIterablePrimitiveClient.puml
!include ../subsets/shared/collectionCommunication/client/primitive/DelegateForwardConstIterablePrimitiveClient.puml
!include ../subsets/shared/collectionCommunication/client/primitive/DelegateForwardIterablePrimitiveClient.puml
!include ../subsets/shared/collectionCommunication/client/primitive/FindUniqueImmutablePrimitiveClient.puml
!include ../subsets/shared/collectionCommunication/client/primitive/FindUniqueMutablePrimitiveClient.puml
!include ../subsets/shared/collectionCommunication/client/primitive/IndexedOperationsPrimitiveClient.puml
!include ../subsets/shared/collectionCommunication/client/primitive/IteratorRelativeInsertionPrimitiveClient.puml
!include ../subsets/shared/collectionCommunication/client/primitive/IteratorRemovePrimitiveClient.puml
!include ../subsets/shared/collectionCommunication/client/primitive/RandomInsertionPrimitiveClient.puml

!include ../subsets/shared/collectionCommunication/client/composite/ContainsOfCompositeClient.puml
!include ../subsets/shared/collectionCommunication/client/composite/FindByImmutableCompositeClient.puml
!include ../subsets/shared/collectionCommunication/client/composite/FindByMutableCompositeClient.puml
!include ../subsets/shared/collectionCommunication/client/composite/FindOfImmutableCompositeClient.puml
!include ../subsets/shared/collectionCommunication/client/composite/FindOfMutableCompositeClient.puml
!include ../subsets/shared/collectionCommunication/client/composite/GenericImmutableStatementsCompositeClient.puml
!include ../subsets/shared/collectionCommunication/client/composite/GenericMutableStatementsCompositeClient.puml
!include ../subsets/shared/collectionCommunication/client/composite/IndicesByCompositeClient.puml
!include ../subsets/shared/collectionCommunication/client/composite/IndicesCompositeClient.puml
!include ../subsets/shared/collectionCommunication/client/composite/IndicesOfCompositeClient.puml
!include ../subsets/shared/collectionCommunication/client/composite/RemoveByCompositeClient.puml
!include ../subsets/shared/collectionCommunication/client/composite/RemoveOfCompositeClient.puml
!include ../subsets/shared/collectionCommunication/client/composite/ReplaceByCompositeClient.puml
!include ../subsets/shared/collectionCommunication/client/composite/ReplaceOfCompositeClient.puml
!include ../subsets/shared/collectionCommunication/client/composite/ReplaceCompositeClient.puml

!include ../subsets/shared/iterator/Iterator.puml
!include ../subsets/shared/delegateIterator/DelegateIteratorAll.puml

@enduml